api_version = "2024-10"

[[extensions]]
name = "DH Tracking Pixel"
handle = "dh-tracking-pixel"
type = "web_pixel_extension"
uid = "2d8efb00-bc5c-7ff2-116f-fca9847eb326644cbcd1"
runtime_context = "strict"

[extensions.runtime_configuration_definition]
type = "object"
properties = {}

[extensions.settings]

[[extensions.settings.fields]]
key = "shop_domain"
type = "single_line_text_field"
name = "Shop Domain"
description = "Your shop domain (automatically populated)"

[extensions.customer_privacy]
analytics = true
marketing = true
preferences = true
sale_of_data = "disabled"
